-- What is the average quantity of products purchased by each payment method?
SELECT payment_method, AVG(quantity) AS average_quantity
FROM customer_shopping_data 
GROUP BY payment_method;


-- Which shopping mall had the highest total revenue in a specific month?
SELECT shopping_mall, SUM(quantity * price) AS total_revenue
FROM customer_shopping_data 
WHERE STR_TO_DATE(invoice_date, '%d/%m/%Y') between '2023-01-01' and '2023-01-31'  
GROUP BY shopping_mall
ORDER BY total_revenue DESC;


-- What is the percentage of male customers who made purchases in each category?
SELECT category, 
(COUNT(DISTINCT CASE WHEN gender = 'male' THEN customer_id END) / COUNT(DISTINCT customer_id) * 100) as male_percentage 
FROM customer_shopping_data 
GROUP BY category;

-- How many customers made purchases of at least $100 using a credit card?
SELECT COUNT(DISTINCT customer_id) AS no_of_customer 
FROM customer_shopping_data 
WHERE payment_method = 'Credit Card' AND price > 100;

-- What is the average price of products purchased by customers in each age group?
SELECT age, AVG(price) 
FROM customer_shopping_data 
GROUP BY age;

-- Which payment method had the highest total revenue in a specific year?
SELECT payment_method, SUM(quantity * price) AS total_revenue
FROM customer_shopping_data
WHERE STR_TO_DATE(invoice_date, '%d/%m/%Y') BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY payment_method ORDER BY total_revenue DESC;

-- How many male customers made purchases in each shopping mall?
SELECT COUNT(DISTINCT customer_id) AS num_of_male_customers, shopping_mall
FROM customer_shopping_data
WHERE gender = 'male'
GROUP BY shopping_mall;

-- What is the average quantity of products purchased by customers in each shopping mall?
SELECT AVG(quantity) AS average_quantity, shopping_mall
FROM customer_shopping_data
GROUP BY shopping_mall;

-- What is the total revenue generated by each payment method?
SELECT payment_method, SUM(quantity*price) AS revenue
FROM customer_shopping_data
GROUP BY payment_method;

-- How many customers made purchases in each category using a debit card?
SELECT COUNT(DISTINCT customer_id) AS num_of_customer, category
FROM customer_shopping_data 
WHERE payment_method='Debit Card'
group by category;
