-- What is the average age of male and female customers?
SELECT gender, AVG(age) AS Average_age FROM customer_shopping_data GROUP BY gender;

-- What is the total revenue generated by the shopping mall?
SELECT category, SUM(quantity * price) AS total_revenue 
FROM customer_shopping_data GROUP BY category;

-- What is the most popular payment method used by customers?
SELECT payment_method, COUNT(*) AS Count FROM customer_shopping_data 
GROUP BY payment_method ORDER BY Count DESC;

-- Which category of products has the highest quantity sold?
SELECT category, SUM(quantity) AS quantity FROM customer_shopping_data 
GROUP BY category ORDER BY quantity DESC;

-- Which shopping mall has the highest sales revenue?
SELECT shopping_mall, sum(quantity * price) AS revenue 
FROM customer_shopping_data GROUP BY shopping_mall 
ORDER BY revenue DESC;

-- How many customers bought the product on 31st of any month? 
SELECT DISTINCT count(customer_id) AS customer_count, invoice_date  FROM customer_shopping_data 
WHERE invoice_date > 30 
GROUP BY invoice_date ORDER BY customer_count DESC;

-- What is the total quantity of products purchased by each age group?
SELECT  age, SUM(quantity) FROM customer_shopping_data 
GROUP BY age;

-- What is the average price of products purchased by male and female customers?
SELECT gender, AVG(price) FROM customer_shopping_data 
GROUP BY gender;

-- How many customers made purchases on a specific date?
SELECT COUNT(DISTINCT customer_id) AS num_customers
FROM customer_shopping_data
WHERE invoice_date = '22/07/2022';

