-- What is the average quantity of products purchased by each payment method?


-- Which shopping mall had the highest total revenue in a specific month?


-- What is the percentage of male customers who made purchases in each category?


-- How many customers made purchases of at least $100 using a credit card?


-- What is the average price of products purchased by customers in each age group?


-- Which payment method had the highest total revenue in a specific year?


-- How many male customers made purchases in each shopping mall?


-- What is the average quantity of products purchased by customers in each shopping mall?


-- What is the total revenue generated by each payment method?
select payment_method, sum(quantity*price) as revenue from customer_shopping_data group by payment_method;

-- How many customers made purchases in each category using a debit card?

